### ISSUE TITLE
promptBeta term

### ISSUE THREAD

**Issue by bbcho** [risktoollib/RTL#4]
It's probably a better idea to make assumptions on the structure of the df (i.e. contracts come in order of expiry) rather than assume that the contract expiry order will be implied in the column names with numbers. I'm going to make that change to the python version.

**Comment by risktoollib** [comment]
depends on the class of the variable. Using numeric is safe in R. Also not worth using expiry in the fit as the contract expiries are more or less equidistant (unless IR term structures where cubic splines are used to fit actual observable data points).
